# This is a config for E2B sandbox template.
# You can use template ID (g9irzrb9ko5zrkdb7dpr) or template name (codecraft-nextjs-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("codecraft-nextjs-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("codecraft-nextjs-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('codecraft-nextjs-test')

team_id = "c8858202-994b-4370-bc47-d7f6d25ac10a"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "codecraft-nextjs-test"
template_id = "g9irzrb9ko5zrkdb7dpr"
